# Generated by Django 4.1.2 on 2023-04-24 04:13

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='QuizQuestion',
            fields=[
                ('question_id', models.IntegerField(auto_created=True, primary_key=True, serialize=False)),
                ('topic', models.CharField(max_length=5000)),
                ('question', models.TextField(max_length=5000)),
                ('option_a', models.CharField(max_length=5000)),
                ('option_b', models.CharField(max_length=5000)),
                ('option_c', models.CharField(max_length=5000)),
                ('option_d', models.CharField(max_length=5000)),
                ('correct_answer', models.CharField(max_length=5000)),
                ('difficulty', models.CharField(max_length=5000)),
                ('cognitive_level', models.CharField(max_length=5000)),
                ('subject', models.CharField(max_length=5000)),
            ],
        ),
        migrations.CreateModel(
            name='ResultScore',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cn_score', models.FloatField()),
                ('dbms_score', models.FloatField()),
                ('oops_score', models.FloatField()),
                ('os_score', models.FloatField()),
                ('total_score', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='ResultUserResponse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_id', models.IntegerField()),
                ('answer', models.CharField(max_length=1)),
            ],
        ),
        migrations.CreateModel(
            name='ResultVisualization',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('CO1_correct', models.IntegerField()),
                ('CO2_correct', models.IntegerField()),
                ('CO3_correct', models.IntegerField()),
                ('CO4_correct', models.IntegerField()),
                ('CO1_total', models.IntegerField()),
                ('CO2_total', models.IntegerField()),
                ('CO3_total', models.IntegerField()),
                ('CO4_total', models.IntegerField()),
                ('easy_correct', models.IntegerField()),
                ('medium_correct', models.IntegerField()),
                ('hard_correct', models.IntegerField()),
                ('easy_total', models.IntegerField()),
                ('medium_total', models.IntegerField()),
                ('hard_total', models.IntegerField()),
                ('sub1_correct', models.IntegerField()),
                ('sub2_correct', models.IntegerField()),
                ('sub3_correct', models.IntegerField()),
                ('sub4_correct', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='ResultTest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('test_date', models.DateTimeField(auto_now_add=True)),
                ('scores', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='technicalquestions_api.resultscore')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('user_responses', models.ManyToManyField(to='technicalquestions_api.resultuserresponse')),
                ('visualization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='technicalquestions_api.resultvisualization')),
            ],
        ),
        migrations.CreateModel(
            name='Results',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('testname', models.CharField(max_length=30)),
                ('oops', models.IntegerField()),
                ('dbms', models.IntegerField()),
                ('cn', models.IntegerField()),
                ('os', models.IntegerField()),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='results', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
