# Generated by Django 4.1.2 on 2023-04-28 13:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobscrape_api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ScrapeJobs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('job_name', models.CharField(max_length=500)),
            ],
        ),
    ]
