# Generated by Django 4.1.2 on 2023-04-28 13:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jobscrape_api', '0002_scrapejobs'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ScrapeJobs',
            new_name='ScrapeJob',
        ),
    ]
